<form id="update_message" action="/message/updatemessage" method="post">
	<fieldset>
		<legend>Edit Message</legend>
		<?php
			foreach($this->message as $message) {
				echo '<label for="message">' . $message['first_name'] . ' ' .  $message['last_name'] . ' Says: </label>';
				echo '<input id="message" name="message" type="text" value="' . $message['message'] . '" />';
				echo '<input id="id" name="id" type="hidden" value="' . $message['message_id'] . '" />';
			}
		?>
		<input class="button" type="submit" value="Save" />
	</fieldset>
</form>
<a class="button" href="/index/cancel">Cancel</a>