<form id="update_author" action="/author/updateauthor" method="post">
	<fieldset>
		<legend>Edit an Author</legend>
		<?php
			foreach($this->author as $author) {
				echo '<label for="first_name">First Name: </label>';
				echo '<input id="frist_name" name="first_name" type="text" value="' . $author['first_name'] . '" />';
				echo '<label for="last_name">Last Name: </label>';
				echo '<input id="last_name" name="last_name" type="text" value="' . $author['last_name'] . '" />';
				echo '<input id="id" name="id" type="hidden" value="' . $author['id'] . '" />';
				echo '<a class="button" href="/author/deleteauthor/id/' . $author['id'] . '">Delete</a>';
			}
		?>
		<input class="button" type="submit" value="Save" />
	</fieldset>
</form>
<a class="button" href="/index/cancel">Cancel</a>