<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Messages</title>
	
	<link type="text/css" href="css/master.css" rel="stylesheet" />
</head>

<body>
	<div id="wrapper">
		<h1>Message Application</h1>
		<div id="controls">
			<h2 class="<?= $this->alert->type ?>"><?= $this->alert->message ?></h2>
			<form id="add_author" action="/author/addauthor" method="post">
				<fieldset>
					<legend>Add an Author</legend>
					<label for="first_name">First Name:</label>
					<input type="text" name="first_name" id="first_name" />
					<label for="last_name">Last Name:</label>
					<input type="text" name="last_name" id="last_name" />
					<input class="button" type="submit" value="Submit" />
				</fieldset>
			</form>
			<form id="edit_form" action="/author/editauthor" method="post">
				<fieldset>
					<legend>Edit an Author</legend>
					<select id="edit_author" name="edit_author">
						<?php
							foreach($this->authors as $author) {
								echo '<option value="' . $author['id'] . '">' . $author['first_name'] . ' ' . $author['last_name'] . '</option>';
							}
						?>
					</select>
					<input class="button" type="submit" value="Edit" />
				</fieldset>
			</form>
			<form id="add_message" action="/message/addmessage" method="post">
				<fieldset>
					<legend>Add a Message</legend>
					<label for="message">Message:</label>
					<input type="text" id="message" name="message" />
					<label for="author">By:</label>
					<select id="author" name="author">
						<?php
							foreach($this->authors as $author) {
								echo '<option value="' . $author['id'] . '">' . $author['first_name'] . ' ' . $author['last_name'] . '</option>';
							}
						?>
					</select>
					<input class="button" type="submit" value="Submit" />
				</fieldset>
			</form>
		</div>
		<h3>Popular Authors</h3>
		<table id="popular_authors">
			<thead>
				<tr>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Total Messages</th>
				</tr>
			</thead>
			<tbody>
				<?php
					foreach($this->popular as $popular) {
						echo '<tr>';
						echo '<td>' . $popular['first_name'] . '</td>';
						echo '<td>' . $popular['last_name'] . '</td>';
						echo '<td>' . $popular['message_count'] . '</td>';
						echo '</tr>';
					}
				?>
			</tbody>
		</table>
		<div id="messages">
			<h3>Messages</h3>
			<?php
				foreach($this->messages as $message) {
					echo '<div class="message">';
					echo '<p>';
					echo '<em>' . $message['first_name'] . ' ' . $message['last_name'] . ': </em>' . $message['message'] . ' ';
					echo '<a class="button" href="/message/deletemessage/id/' . $message['message_id'] . ' ' . '">Delete</a> ';
					echo '<a class="button" href="/message/editmessage/id/' . $message['message_id'] . ' ' . '">Edit</a>';
					echo '</p>';
					echo '</div>';  
				}
			?>
		</div>
		<?= $this->layout()->content ?>
	</div>
</body>
</html>