<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Untitled Document</title>
</head>

<body>
	<div id="wrapper">
		<div id="controls">
			<form id="add_author" action="/author/addauthor" method="post">
				<fieldset>
					<legend>Add an Author</legend>
					<label for="first_name">First</label>
					<input type="text" name="first_name" id="first_name" value="first"/>
					<label for="last_name">Last</label>
					<input type="text" name="last_name" id="last_name" value="last"/>
					<input type="submit" value="Submit" />
				</fieldset>
			</form>
			<form action="/author/editauthor" method="post">
				<fieldset>
					<legend>Edit an Author</legend>
					<select id="edit_author" name="edit_author">
						<?php
							foreach($this->authors as $author) {
								echo '<option value="' . $author['id'] . '">' . $author['first_name'] . ' ' . $author['last_name'] . '</option>';
							}
						?>
					</select>
					<input type="submit" value="Edit" />
				</fieldset>
			</form>
			<form id="add_message" action="/message/addmessage" method="post">
				<fieldset>
					<legend>Add a Message</legend>
					<label for="message">Message</label>
					<input type="text" id="message" name="message" />
					<label for="author">By:</label>
					<select id="author" name="author">
						<?php
							foreach($this->authors as $author) {
								echo '<option value="' . $author['id'] . '">' . $author['first_name'] . ' ' . $author['last_name'] . '</option>';
							}
						?>
					</select>
					<input type="submit" value="Submit" />
				</fieldset>
			</form>
		</div>
		<h2><?= $this->alert->message ?></h2>
		<div id="messages">
			<?php
				foreach($this->messages as $message) {
					echo '<div>';
					echo '<p>';
					echo $message['message'];
					echo '<a href="/message/deletemessage/id/' . $message['id'] . ' ' . '">Delete</a>';
					echo '</p>';
					echo '</div>';  
				}
			?>
		</div>
		<?= $this->layout()->content ?>
	</div>
</body>
</html>