<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
	<title>Untitled Document</title>
</head>

<body>
	<div id="wrapper">
		<div id="controls">
			<form id="add_author" action="addAuthor" method="post">
				<fieldset>
					<label for="new_author">Add an Author</label>
					<input type="text" name="new_author" id="new_author" />
					<input type="submit" value="Submit" />
				</fieldset>
			</form>
			<form id="add_message" action="addMessage" method="post">
				<fieldset>
					<label for="message">Message</label>
					<input type="text" id="message" name="message" />
					<label for="author">By:</label>
					<select>
						<option value="default">default</option>
					</select>
					<input type="submit" value="Submit" />
				</fieldset>
			</form>
		</div>
		<?= $this->layout()->content ?>
	</div>
	<p>Basic Page</p>
</body>
</html>